version: '3'
services:
  tnp:
    image: 'hydiant/tnp:latest'
    build: .
    environment:
    - TNP_PROJECT=${TNP_PROJECT}
    - TNP_BUCKET=${TNP_BUCKET}
    command:
    - server.up
    ports:
    - 8080:8080
    volumes:
    - ~/.config/gcloud:/root/.config/gcloud
